### PR TITLE
Update dependencies versions due to security alerts

### PR DESCRIPTION
**Pull request by jzolnowski**
Due to security alerts:
- [vm2 Sandbox Escape vulnerability](https://github.com/xlts-dev/angularjs-angular-hybrid-angular-cli/security/dependabot/96)
- [vm2 vulnerable to Inspect Manipulation](https://github.com/xlts-dev/angularjs-angular-hybrid-angular-cli/security/dependabot/97)
- [Cross site scripting in Angular](https://github.com/xlts-dev/angularjs-angular-hybrid-angular-cli/security/dependabot/78)

The first two alerts are related to the installed version `3.9.17` of `vm2`, which is a dependency of the dependency of `firebase-tools@11.30.0`. Both problems have been fixed in the release of version `3.9.18` of `vm2`. By installing `firebase-tools v12.3.0`, we install the `vm2` dependency version `3.9.19`, which fixes the mentioned errors.

The last issue is related to packages associated with `Angular v15.2.8` and is related to comment handling, where manipulation leads to cross site scripting. Upgrading the packages to `v15.2.9` resolves this issue.

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
I see that you also update the lockfile version. Is that intentional? If so, I think it is worth mentioning in the commit message. Also, please make sure the commit message follows the commit message guidelines.

**Comment by jzolnowski** [comment]
> I see that you also update the lockfile version. Is that intentional? If so, I think it is worth mentioning in the commit message. Also, please make sure the commit message follows the commit message guidelines.

This is intentional, because we migrated to npm v9, and this npm version [uses lockfileVersion: 3](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#file-format)

Updated commit message 😄

**Comment by gkalpak** [comment]
This PR is unrelated to the npm@9 migration, so bumping the lockfile version on the commit that addresses security issues seems irrelevant (unless it is necessary to fix said security issues). I am fine with updating the lockfile version, but it should be on a separate PR (or commit).

Also, please make sure the commit message follows the commit message guidelines :pray:

**Comment by jzolnowski** [comment]
thank you @gkalpak for your comment. I removed changes regarding bump `lockfileVersion` to 3 from this PR. Created a [separate PR](https://github.com/xlts-dev/angularjs-angular-hybrid-angular-cli/pull/18) for update `lockfileVersion`. Also improved a bit the commit message

**Review by gkalpak — CHANGES_REQUESTED** [review]
Thx for splitting the PR. The commit still doesn't seem to be following the [guidelines][1] 😕

[1]: https://github.com/xlts-dev/angular.js/blob/4220d562cfcc67a83720d0eadf169710783edeb2/DEVELOPERS.md#-git-commit-guidelines

**Comment by jzolnowski** [comment]
@gkalpak commit message updated 😄

**Review by Splaktar — APPROVED** [review]

**Review by gkalpak — APPROVED** [review]
Looks great :100:
Thank you!

**Pull request merged**
