### PR TITLE
chore(package-lock): bump lockfileVersion to 3

### PR DESCRIPTION
**Pull request by jzolnowski**
Due to the fact that we define a  property in package.json that sets the npm version to higher/equal to v9, we need to rebuild package-lock.json and set  to 3 due it's used by default with npm v9 - [more details](https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#file-format)

### CODE REVIEW

**Review by gkalpak — CHANGES_REQUESTED** [review]
Running `npm install` with npm v9.5.0 and npm v9.5.1 (with Node.js v18.15.0 and v18.16.0 respectively) results in some updates to the lockfile. What npm version do you run the update with?

(Nice commit message btw :wink:)

**Comment by jzolnowski** [comment]
> Running `npm install` with npm v9.5.0 and npm v9.5.1 (with Node.js v18.15.0 and v18.16.0 respectively) results in some updates to the lockfile. What npm version do you run the update with?
> 

@gkalpak I'm using node v18.15.0 and npm v9.5.0

**Comment by gkalpak** [comment]
@jzolnowski, I've merged #17. Please rebase this on master and make sure the lockfile is updated :pray:

**Comment by jzolnowski** [comment]
> @jzolnowski, I've merged #17. Please rebase this on master and make sure the lockfile is updated 🙏

Done

**Review by gkalpak — APPROVED** [review]
LGTM 🚀

**Pull request merged**
